// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
