// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, owner_id)
VALUES ($1, $2)
ON CONFLICT (name, owner_id) DO UPDATE SET updated_at = NOW()
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateItemParams struct {
	Name    string
	OwnerID string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.Name, arg.OwnerID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, owner_id, created_at, updated_at FROM items WHERE id = $1 LIMIT 1
`

func (q *Queries) GetItemByID(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsByOwner = `-- name: ListItemsByOwner :many
SELECT id, name, owner_id, created_at, updated_at FROM items WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListItemsByOwner(ctx context.Context, ownerID string) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteItemByID = `-- name: DeleteItemByID :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItemByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemByID, id)
	return err
}
