FROM golang:1.27-bookworm

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GO111MODULE=on

WORKDIR /build
ADD ./ ./

RUN go build -o /opt/example ./services/example/cmd/example

RUN groupadd example && useradd -g example example -d /home/example && \
    chown -R example:example /opt/example && chmod +x /opt/example

USER example
EXPOSE 8080
CMD ["/opt/example"]
